spring:
    config:
        activate:
            on-profile: default
    cache:
        type: redis
logging:
    level:
        com:
            interviews:
                jai: 
                    geico:
                        eras: DEBUG